resources:
  repositories:
    - repository: ReleaseNotesGenerator
      type: github
      endpoint: syedhassanabbas
      name: syedhassanabbas/ReleaseNotesGenerator
      ref: refs/heads/main

trigger:
- main

pool: Default

stages:

  - stage: build   
    jobs:
      - job: buildjob        
        steps:
          - checkout: ReleaseNotesGenerator
          - task: CmdLine@2
            displayName: 'List files'
            inputs:
              script: |
                dir /a-D /S /B
              workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - stage: Devv
    jobs:
      - job: manualValidation
        displayName: Validate Infra Changes on Dev
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:   
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              notifyUsers: |
                  [HassanAbbasShahSoftLTD]\Project DevOps Engineer
              instructions: 'Please validate the terraform plan and resume'
              onTimeout: 'resume'

      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default
        environment: 'Devv'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Devv deployment
  - stage: Test
    jobs:
      - job: manualValidation
        displayName: Validate Infra Changes on Test  
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:   
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              notifyUsers: |
                  [HassanAbbasShahSoftLTD]\Project DevOps Engineer
              instructions: 'Please validate the terraform plan and resume'
              onTimeout: 'resume'

      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default
        environment: 'Test'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Test deployment
  - stage: Stag
    jobs:
      - job: manualValidation
        displayName: Validate Infra Changes on Staging  
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:   
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              notifyUsers: |
                  [HassanAbbasShahSoftLTD]\Operational DevOps Engineer
              instructions: 'Please validate the terraform plan and resume'
              onTimeout: 'resume'

      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default
        environment: 'Stag'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Test deployment
  - stage: Prod
    jobs:
      - job: manualValidation
        displayName: Validate Infra Changes on Production  
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:   
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              notifyUsers: |
                  [HassanAbbasShahSoftLTD]\Operational DevOps Engineer
              instructions: 'Please validate the terraform plan and resume'
              onTimeout: 'resume'

      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default
        environment: 'Prod'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Test deployment