name: $(Major).$(Minor).$(rev:r) 

resources:
  repositories:
    - repository: ReleaseNotesGenerator
      type: github
      endpoint: syedhassanabbas
      name: syedhassanabbas/ReleaseNotesGenerator
      ref: refs/heads/main      

trigger:
- main

pool: Default

stages:

  - stage: build   
    jobs:
      - job: buildjob        
        steps:
          - checkout: ReleaseNotesGenerator
          - powershell: |
              Write-Host "Show all folder content"
              Get-ChildItem -Path $(Build.SourcesDirectory)\*.* -Recurse -Force
            errorActionPreference: continue
            displayName: 'PowerShell Script List folder structure'
            continueOnError: true
  - stage: Devv
    jobs:
      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default  
        environment: 'Devv'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Test deployment
              - template: generate-wiki-docs.yml
                parameters:
                  environmentName: "Devv"

      #   - task: WikiUpdaterTask@1
      #   displayName: 'Git based WIKI Updater'
      #   inputs:
      #     repo: 'dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki'
      #     filename: 'xPlatReleaseNotes/build-Windows-handlebars.md'
      #     dataIsFile: true
      #     sourceFile: '$(System.DefaultWorkingDirectory)inline.md'
      #     message: 'Update from Build'
      #     gitname: builduser
      #     gitemail: 'build@demo'
      #     useAgentToken: true

      # - deployment: DeployWeb
      #   displayName: deploy Web App
      #   pool: Default
      #   environment: 'Devv'
      #   strategy:
      #     # default deployment strategy 
      #     runOnce:
      #       deploy:
      #         steps:
      #         - script: echo my Devv deployment
  - stage: Test
    jobs:
      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default        
        environment: 'Test'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Test deployment
              - template: generate-wiki-docs.yml
                parameters:
                  environmentName: "Test"
  - stage: Stag
    jobs:
      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default       
        environment: 'Stag'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Test deployment
              - template: generate-wiki-docs.yml
                parameters:
                  environmentName: "stag"
  - stage: Prod
    jobs:
      - deployment: DeployWeb
        displayName: deploy Web App
        pool: Default  
        environment: 'Prod'
        strategy:
          # default deployment strategy 
          runOnce:
            deploy:
              steps:
              - script: echo my Prod deployment
              - template: generate-wiki-docs.yml
                parameters:
                  environmentName: "Prod"
